### PR TITLE
use time.Data/time.Clock to get hour,min, sec, year, month, day

### PR DESCRIPTION
**Pull request by jiangtao244**

### CODE REVIEW

**Comment by jinzhu** [comment]
what's the problem to resolve?

**Comment by jiangtao244** [comment]
This can reduce CPU usage.
No need to call the inner functions three times.

**Comment by jinzhu** [comment]
Could you extract a helper? so we don't need to write it three times?

**Comment by jinzhu** [comment]
thank you for your PR.

**Pull request merged**
